/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;


public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginBTN = new javax.swing.JButton();
        loginBTN2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        loginBTN5 = new javax.swing.JButton();
        loginBTN6 = new javax.swing.JButton();
        loginBTN7 = new javax.swing.JButton();
        loginBTN8 = new javax.swing.JButton();
        addclass = new javax.swing.JButton();
        addclass1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        loginBTN.setBackground(new java.awt.Color(102, 102, 102));
        loginBTN.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        loginBTN.setForeground(new java.awt.Color(204, 204, 204));
        loginBTN.setText("Add Student");
        loginBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBTNActionPerformed(evt);
            }
        });

        loginBTN2.setBackground(new java.awt.Color(102, 102, 102));
        loginBTN2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        loginBTN2.setForeground(new java.awt.Color(204, 204, 204));
        loginBTN2.setText("Show Students");
        loginBTN2.setBorderPainted(false);
        loginBTN2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBTN2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Dashboard");

        loginBTN5.setBackground(new java.awt.Color(102, 102, 102));
        loginBTN5.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        loginBTN5.setForeground(new java.awt.Color(204, 204, 204));
        loginBTN5.setText("Configure");
        loginBTN5.setBorderPainted(false);
        loginBTN5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBTN5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBTN5ActionPerformed(evt);
            }
        });

        loginBTN6.setBackground(new java.awt.Color(102, 102, 102));
        loginBTN6.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        loginBTN6.setForeground(new java.awt.Color(204, 204, 204));
        loginBTN6.setText("Show Admin");
        loginBTN6.setBorderPainted(false);
        loginBTN6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBTN6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBTN6ActionPerformed(evt);
            }
        });

        loginBTN7.setBackground(new java.awt.Color(102, 102, 102));
        loginBTN7.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        loginBTN7.setForeground(new java.awt.Color(204, 204, 204));
        loginBTN7.setText("Add Admin");
        loginBTN7.setBorderPainted(false);
        loginBTN7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBTN7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBTN7ActionPerformed(evt);
            }
        });

        loginBTN8.setBackground(new java.awt.Color(102, 102, 102));
        loginBTN8.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        loginBTN8.setForeground(new java.awt.Color(204, 204, 204));
        loginBTN8.setText("Configure");
        loginBTN8.setBorderPainted(false);
        loginBTN8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBTN8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBTN8ActionPerformed(evt);
            }
        });

        addclass.setBackground(new java.awt.Color(102, 102, 102));
        addclass.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        addclass.setForeground(new java.awt.Color(204, 204, 204));
        addclass.setText("Add Class");
        addclass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addclassActionPerformed(evt);
            }
        });

        addclass1.setBackground(new java.awt.Color(102, 102, 102));
        addclass1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        addclass1.setForeground(new java.awt.Color(204, 204, 204));
        addclass1.setText("Show Classes");
        addclass1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addclass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addclass1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(loginBTN5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(loginBTN2, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(loginBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addclass1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addclass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginBTN7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginBTN6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginBTN8, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(loginBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(loginBTN2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(loginBTN5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loginBTN7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addclass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loginBTN6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addclass1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(loginBTN8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(233, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(new java.awt.Color(204, 204, 204));
        jMenuBar1.setBorderPainted(false);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jMenuBar1.setOpaque(true);

        jMenu1.setBorder(null);
        jMenu1.setForeground(new java.awt.Color(51, 51, 51));
        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\home (1).png")); // NOI18N
        jMenuItem2.setText("Home");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\log-out.png")); // NOI18N
        jMenuItem1.setText("Log Out");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(null);
        jMenu2.setText("Edit");
        jMenu2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\magnify (1).png")); // NOI18N
        jMenuItem3.setText("About");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(651, 494));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBTNActionPerformed
                    setVisible(false);
                    AddStudent h1 = new AddStudent();
                    h1.setVisible(true);
    }//GEN-LAST:event_loginBTNActionPerformed

    private void loginBTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBTN2ActionPerformed
                    setVisible(false);
                    showStudent h1 = new showStudent();
                    h1.setVisible(true);
    }//GEN-LAST:event_loginBTN2ActionPerformed

    private void loginBTN5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBTN5ActionPerformed
                    setVisible(false);
                    Student h1 = new Student();
                    h1.setVisible(true);
    }//GEN-LAST:event_loginBTN5ActionPerformed

    private void loginBTN6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBTN6ActionPerformed
                    setVisible(false);
                    showAdmin h1 = new showAdmin();
                    h1.setVisible(true);
    }//GEN-LAST:event_loginBTN6ActionPerformed

    private void loginBTN7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBTN7ActionPerformed
                    setVisible(false);
                    addAdmin h1 = new addAdmin();
                    h1.setVisible(true);
    }//GEN-LAST:event_loginBTN7ActionPerformed

    private void loginBTN8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBTN8ActionPerformed
                setVisible(false);
                    Admin h1 = new Admin();
                    h1.setVisible(true);
    }//GEN-LAST:event_loginBTN8ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
                    setVisible(false);
                    About h1 = new About();
                    h1.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
                    setVisible(false);
                    Login h1 = new Login();
                    h1.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
                    setVisible(false);
                    Dashboard h1 = new Dashboard();
                    h1.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void addclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addclassActionPerformed
                    setVisible(false);
                    Classes h1 = new Classes();
                    h1.setVisible(true);
    }//GEN-LAST:event_addclassActionPerformed

    private void addclass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addclass1ActionPerformed
                    setVisible(false);
                    showClass h1 = new showClass();
                    h1.setVisible(true);
    }//GEN-LAST:event_addclass1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addclass;
    private javax.swing.JButton addclass1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBTN;
    private javax.swing.JButton loginBTN2;
    private javax.swing.JButton loginBTN5;
    private javax.swing.JButton loginBTN6;
    private javax.swing.JButton loginBTN7;
    private javax.swing.JButton loginBTN8;
    // End of variables declaration//GEN-END:variables
}
